language: erlang
otp_release:
   - R15B02
   - R16B02

before_script:
  - sudo apt-get install libpcap-dev

# Use "make test" instead of default "rebar eunit", to exclude
# linc_us3 tests.
script: "make test"
